# Generated by Django 5.2 on 2025-04-25 18:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='default-ui-image.png', null=True, upload_to=''),
        ),
    ]
